const FEEDBACK_ENDPOINT = "https://script.google.com/macros/s/AKfycbxuFHf4WlRXYq2I0QJdC5D3zolFzg70moOFoKJIwDklQRfugmD8LYsl4JZ3Z9hTIonhKw/exec";
document.addEventListener("DOMContentLoaded", ()=>{loadResources();loadQuizTopics();bindFeedbackForm();bindAdmin();});
async function loadResources(){try{const res=await fetch('resources.json?t='+Date.now());const items=await res.json();const container=document.getElementById('resourceCards')||document.getElementById('topicsList');if(!container) return;container.innerHTML='';items.forEach(it=>{const card=document.createElement('div');card.className='card';const icon=it.type==='pdf'?'📄':(it.type==='image'?'🖼️':'📑');card.innerHTML=`<div class="icon">${icon}</div><div class="resource-title">${it.title}</div><div class="resource-summary">${it.summary}</div><div style="margin-top:.6rem"><button onclick="openPreview('${it.preview||''}','${it.file}')">Preview</button> <a href="${it.file}" download>Download</a></div>`;container.appendChild(card)});}catch(e){console.warn('No resources.json yet',e);}}
function openPreview(previewPath,filePath){if(previewPath){const w=window.open(previewPath,'_blank');if(!w) alert('Popup blocked: preview available in new tab via download link');} else {window.open(filePath,'_blank');}}
async function loadQuizTopics(){try{const res=await fetch('quiz.json?t='+Date.now());const q=await res.json();const sel=document.getElementById('topicSelect');if(!sel) return;const topics=Array.from(new Set(q.map(x=>x.topic||'General')));topics.forEach(t=>{const opt=document.createElement('option');opt.value=t;opt.innerText=t;sel.appendChild(opt)});document.getElementById('startQuiz').addEventListener('click',()=>startQuiz(sel.value));}catch(e){console.warn('No quiz.json yet',e)}}
function startQuiz(topic){fetch('quiz.json?t='+Date.now()).then(r=>r.json()).then(list=>{const pool=(topic==='all')?list:list.filter(q=>q.topic===topic);if(!pool.length){alert('No questions for this topic yet');return}const picks=shuffle(pool).slice(0,7);renderQuiz(picks);});}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function renderQuiz(questions){const area=document.getElementById('quizArea');area.innerHTML='';let score=0;questions.forEach((q,idx)=>{const div=document.createElement('div');div.className='card';div.innerHTML = `<h4>Q${idx+1}. ${q.q}</h4>` + q.options.map((o,i)=>`<button onclick="answer(this,${i},${idx})">${o}</button>`).join('');area.appendChild(div);window._quiz = window._quiz || {}; window._quiz.questions = questions; window._quiz.answered = window._quiz.answered || {};});const resultBtn=document.createElement('button');resultBtn.innerText='Submit';resultBtn.onclick=showQuizResult;area.appendChild(resultBtn);}
function answer(btn,optIndex,qIdx){const q=window._quiz.questions[qIdx];if(window._quiz.answered[qIdx]) return;const selected=q.options[optIndex];const correct=q.a;if(selected===correct){btn.style.background='lightgreen';window._quiz.score=(window._quiz.score||0)+1;}else{btn.style.background='#ffb4b4'}window._quiz.answered[qIdx]=selected;if(window.gtag) gtag('event','quiz_answer',{event_label: q.q, value: selected});}
function showQuizResult(){alert('Score: '+(window._quiz.score||0)+' / '+window._quiz.questions.length);if(window.gtag) gtag('event','quiz_complete',{event_label:'quiz', value: window._quiz.score||0});}
function bindFeedbackForm(){const form=document.getElementById('feedbackForm');if(!form) return;const status=document.getElementById('feedbackStatus');form.addEventListener('submit',async (e)=>{e.preventDefault();const name=document.getElementById('f_name').value;const email=document.getElementById('f_email').value;const message=document.getElementById('f_msg').value;const files=document.getElementById('f_files').files;const filePayload=[];for(let i=0;i<files.length;i++){const f=files[i];const dataURL=await new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(f);});const base64=dataURL.split(',')[1];filePayload.push({name:f.name,type:f.type,content:base64})}const payload={name,email,message,files:filePayload};const resp=await fetch(FEEDBACK_ENDPOINT,{method:'POST',body:JSON.stringify(payload),headers:{'Content-Type':'application/json'}});const j=await resp.json();if(j.status==='success'){status.innerText='Thanks! Feedback received 🚀';form.reset();}else{status.innerText='Error sending feedback'}});}
function bindAdmin(){const btn=document.getElementById('unlockAdmin');if(!btn) return;btn.addEventListener('click',()=>{const pass=document.getElementById('adminPass').value; if(pass==='shirooni123'){document.getElementById('adminArea').style.display='block';document.getElementById('adminFeedback').innerText='(Admin data will appear here)';} else alert('Wrong passcode');});}
function translateText(text){window.open('https://translate.google.com/?sl=auto&tl=en&text='+encodeURIComponent(text)+'&op=translate','_blank');}