name: Auto Cleanup Repo

on:
  push:
    branches: [ "main" ]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run cleanup script
        run: |
          echo "Running cleanup..."
          python cleanup_repo.py

      - name: Commit changes if any
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Auto cleanup repo" || echo "No cleanup needed"
          git push
          
